name: update-repos-list

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: evoteum/estate-repos
          path: estate-repos
          sparse-checkout: repos.yaml

      - name: Replace content in profile/README.md
        run: |
          FILE="profile/README.md"
          START="[//]: # (REPOS_START)"
          END="[//]: # (REPOS_END)"

          # Extract existing content before and after markers
          awk -v start="$START" -v end="$END" '
            BEGIN {p=1}
            $0 ~ start {print; p=0; print "```yaml"; system("cat estate-repos/repos.yaml"); print "```"; next}
            $0 ~ end {p=1}
            p
          ' "$FILE" > temp.md && mv temp.md "$FILE"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add profile/README.md
          git diff --cached --quiet || (git commit -m "Update repos list from estate-repos" && git push origin main)